#!/usr/bin/env python3
"""Cross-platform RSAP local runtime runner."""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import signal
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib import error, request


CENTRAL_BACKEND_URL = "http://localhost:8000"
FILE_SERVER_URL = "http://localhost:8002"
CENTRAL_FRONTEND_URL = "http://localhost:3000"
DESKTOP_BACKEND_URL = "http://127.0.0.1:8001"
DESKTOP_FRONTEND_URL = "http://127.0.0.1:1420"

DOCKER_SERVICES = [
    "postgres",
    "redis",
    "minio",
    "webapp-backend",
    "file-server",
    "webapp-frontend",
    "caddy",
]

LOCAL_ENV_TEMPLATE = """# Generated by scripts/run-all.py for local development only.
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=rsap
POSTGRES_USER=rsap_user
POSTGRES_PASSWORD=postgres123

REDIS_PASSWORD=redis123
REDIS_URL=redis://:redis123@redis:6379/0

MINIO_ENDPOINT=minio:9000
MINIO_SECURE=false
MINIO_INTERNAL_ENDPOINT=minio:9000
MINIO_INTERNAL_SECURE=false
MINIO_PUBLIC_ENDPOINT=localhost:9000
MINIO_PUBLIC_SECURE=false
MINIO_ACCESS_KEY=rsapminio
MINIO_SECRET_KEY=miniosecret123
MINIO_BUCKET_FACES=faces
MINIO_BUCKET_CAPTURES=captures
MINIO_BUCKET_DOCUMENTS=documents
MINIO_REGION=us-east-1

JWT_SECRET=jwtsecret123456789012345678901234
JWT_ALGORITHM=HS256
JWT_ACCESS_EXPIRE_MINUTES=15
JWT_REFRESH_EXPIRE_DAYS=7

AES_ENCRYPTION_KEY=12345678901234567890123456789012

APP_ENV=development
APP_DOMAIN=rsap.local
ADMIN_EMAIL=admin@rsap.local
ADMIN_PASSWORD=admin123
FILE_SERVER_SERVICE_TOKEN=filetoken123456
LICENSE_SIGNING_SECRET=licensesecret123456
CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,tauri://localhost
NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
RSAP_BACKEND_URL=http://localhost:8000
RSAP_FILE_SERVER_URL=http://localhost:8002
"""


class RunnerError(RuntimeError):
    """Raised for expected runner failures."""


def is_windows() -> bool:
    return platform.system().lower().startswith("win")


def find_repo_root(start: Path | None = None) -> Path:
    current = (start or Path(__file__).resolve()).resolve()
    if current.is_file():
        current = current.parent
    for candidate in (current, *current.parents):
        if (candidate / "infra" / "docker-compose.yml").is_file() and (candidate / "scripts").is_dir():
            return candidate
    raise RunnerError("Could not find repository root from current path.")


def runtime_dir(root: Path) -> Path:
    path = root / ".runtime"
    path.mkdir(exist_ok=True)
    return path


def metadata_path(root: Path) -> Path:
    return runtime_dir(root) / "rsap-runner.json"


def compose_command(root: Path, *args: str, include_dev: bool = True) -> list[str]:
    command = [
        "docker",
        "compose",
        "--env-file",
        str(root / ".env"),
        "-f",
        str(root / "infra" / "docker-compose.yml"),
    ]
    if include_dev:
        command += ["-f", str(root / "infra" / "docker-compose.dev.yml")]
    return command + list(args)


def run(command: list[str], *, cwd: Path, env: dict[str, str] | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    command = resolve_command(command)
    print(f"$ {' '.join(command)}")
    try:
        completed = subprocess.run(command, cwd=cwd, env=env, text=True)
    except FileNotFoundError as exc:
        raise RunnerError(f"Command not found: {command[0]}") from exc
    if check and completed.returncode != 0:
        raise RunnerError(f"Command failed with exit code {completed.returncode}: {' '.join(command)}")
    return completed


def run_capture(command: list[str], *, cwd: Path, check: bool = True) -> subprocess.CompletedProcess[str]:
    command = resolve_command(command)
    completed = subprocess.run(command, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if completed.stdout:
        print(completed.stdout.rstrip())
    if check and completed.returncode != 0:
        raise RunnerError(f"Command failed with exit code {completed.returncode}: {' '.join(command)}")
    return completed


def resolve_command(command: list[str]) -> list[str]:
    resolved = shutil.which(command[0])
    if resolved:
        return [resolved, *command[1:]]
    return command


def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def ensure_env(root: Path) -> Path:
    env_path = root / ".env"
    if env_path.exists():
        print(f"[ok] Using existing {env_path}")
        return env_path
    env_path.write_text(LOCAL_ENV_TEMPLATE, encoding="utf-8", newline="\n")
    print(f"[ok] Created local development {env_path}")
    return env_path


def should_install(path: Path, mode: str) -> bool:
    if mode == "always":
        return True
    if mode == "never":
        return False
    return not path.exists()


def python_launcher() -> list[str]:
    if is_windows():
        return ["py", "-3.12"]
    return ["python3.12"]


def fallback_python_launcher() -> list[str]:
    return [sys.executable]


def ensure_desktop_backend(root: Path, install_mode: str) -> Path:
    backend = root / "apps" / "desktop-backend"
    venv = backend / ".venv"
    python_exe = venv / ("Scripts/python.exe" if is_windows() else "bin/python")
    if should_install(venv, install_mode):
        launcher = python_launcher()
        try:
            run(launcher + ["-m", "venv", ".venv"], cwd=backend)
        except RunnerError:
            if not venv.exists():
                print("[warn] Python 3.12 launcher failed; falling back to the current Python.")
                run(fallback_python_launcher() + ["-m", "venv", ".venv"], cwd=backend)
        for requirements in ("requirements.txt", "requirements-dev.txt", "requirements-orchestration-dev.txt"):
            run([str(python_exe), "-m", "pip", "install", "-r", requirements], cwd=backend)
        run([str(python_exe), "-m", "pip", "install", "-e", str(root / "packages" / "cv-engine")], cwd=backend)
    elif not python_exe.exists():
        raise RunnerError(f"Desktop backend venv is missing. Run with --install: {venv}")
    else:
        print(f"[ok] Desktop backend venv exists: {venv}")
    return python_exe


def ensure_desktop_frontend(root: Path, install_mode: str) -> None:
    frontend = root / "apps" / "desktop-frontend"
    node_modules = frontend / "node_modules"
    if should_install(node_modules, install_mode):
        run(["npm", "install"], cwd=frontend)
    elif not node_modules.exists():
        raise RunnerError(f"Desktop frontend node_modules is missing. Run with --install: {node_modules}")
    else:
        print(f"[ok] Desktop frontend node_modules exists: {node_modules}")


def desktop_backend_env(root: Path) -> dict[str, str]:
    data_dir = Path.home() / ".rsap"
    data_dir.mkdir(exist_ok=True)
    env = os.environ.copy()
    env.update(
        {
            "RSAP_ENVIRONMENT": "test",
            "RSAP_HOST": "127.0.0.1",
            "RSAP_PORT": "8001",
            "RSAP_DATABASE_DRIVER": "sqlite-test",
            "RSAP_DATA_DIR": str(data_dir),
            "RSAP_DATABASE_PATH": str(data_dir / "local.db"),
            "RSAP_DATABASE_KEY": "lKU8bhA9wUhK9gYp0xN0DsZBI0JzjVwDhv43qG0GvhY",
            "RSAP_FIELD_ENCRYPTION_KEY": "zIx0m0ojkkJ1bEzN8S48o3IdtxB7Dt8cbAcRng9Jv7U",
            "RSAP_CENTRAL_API_URL": CENTRAL_BACKEND_URL,
            "RSAP_FILE_SERVER_URL": FILE_SERVER_URL,
        }
    )
    return env


def load_metadata(root: Path) -> dict[str, Any]:
    path = metadata_path(root)
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def write_metadata(root: Path, metadata: dict[str, Any]) -> None:
    metadata_path(root).write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")


def pid_alive(pid: int | None) -> bool:
    if not pid:
        return False
    if is_windows():
        completed = subprocess.run(
            ["tasklist", "/FI", f"PID eq {pid}"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return str(pid) in completed.stdout
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def stop_pid(pid: int | None, name: str) -> None:
    if not pid or not pid_alive(pid):
        print(f"[ok] {name} is not running")
        return
    print(f"[info] Stopping {name} pid {pid}")
    if is_windows():
        subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    else:
        try:
            os.killpg(pid, signal.SIGTERM)
        except OSError:
            os.kill(pid, signal.SIGTERM)
    deadline = time.time() + 10
    while time.time() < deadline:
        if not pid_alive(pid):
            print(f"[ok] Stopped {name}")
            return
        time.sleep(0.25)
    if not is_windows():
        try:
            os.killpg(pid, signal.SIGKILL)
        except OSError:
            pass


def start_process(command: list[str], *, cwd: Path, env: dict[str, str] | None, log_path: Path) -> subprocess.Popen[Any]:
    command = resolve_command(command)
    log = log_path.open("ab")
    kwargs: dict[str, Any] = {
        "cwd": cwd,
        "env": env,
        "stdout": log,
        "stderr": subprocess.STDOUT,
        "stdin": subprocess.DEVNULL,
    }
    if is_windows():
        kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
    else:
        kwargs["start_new_session"] = True
    return subprocess.Popen(command, **kwargs)


def start_desktop_processes(root: Path, python_exe: Path) -> dict[str, Any]:
    existing = load_metadata(root)
    backend_pid = existing.get("desktop_backend_pid")
    frontend_pid = existing.get("desktop_frontend_pid")
    if pid_alive(backend_pid) and pid_alive(frontend_pid):
        print("[ok] Runner-managed desktop processes are already running")
        return existing

    stop_pid(backend_pid, "desktop-backend")
    stop_pid(frontend_pid, "desktop-frontend")

    logs = runtime_dir(root)
    backend = root / "apps" / "desktop-backend"
    frontend = root / "apps" / "desktop-frontend"
    backend_process = start_process(
        [str(python_exe), "-m", "uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8001"],
        cwd=backend,
        env=desktop_backend_env(root),
        log_path=logs / "desktop-backend.log",
    )
    frontend_process = start_process(
        ["npm", "run", "dev", "--", "--host", "127.0.0.1", "--port", "1420"],
        cwd=frontend,
        env=os.environ.copy(),
        log_path=logs / "desktop-frontend.log",
    )
    time.sleep(2)
    failed = []
    if backend_process.poll() is not None:
        failed.append(("desktop-backend", backend_process.returncode, logs / "desktop-backend.log"))
    if frontend_process.poll() is not None:
        failed.append(("desktop-frontend", frontend_process.returncode, logs / "desktop-frontend.log"))
    if failed:
        for process in (backend_process, frontend_process):
            if process.poll() is None:
                stop_pid(process.pid, "partially-started desktop process")
        details = "; ".join(
            f"{name} exited with {code}. Last log lines: {tail_log(log_path)}"
            for name, code, log_path in failed
        )
        raise RunnerError(details)
    metadata = {
        "desktop_backend_pid": backend_process.pid,
        "desktop_frontend_pid": frontend_process.pid,
        "started_at": datetime.now(timezone.utc).isoformat(),
        "urls": {
            "desktop_backend": DESKTOP_BACKEND_URL,
            "desktop_frontend": DESKTOP_FRONTEND_URL,
        },
    }
    write_metadata(root, metadata)
    print(f"[ok] Started desktop-backend pid {backend_process.pid}")
    print(f"[ok] Started desktop-frontend pid {frontend_process.pid}")
    return metadata


def tail_log(path: Path, lines: int = 12) -> str:
    if not path.exists():
        return "<log missing>"
    content = path.read_text(encoding="utf-8", errors="replace").splitlines()
    return " | ".join(content[-lines:]) or "<log empty>"


def http_get(url: str, timeout: int = 10) -> tuple[int, bytes]:
    with request.urlopen(url, timeout=timeout) as response:
        return response.status, response.read()


def http_json(url: str, timeout: int = 10) -> Any:
    status, body = http_get(url, timeout)
    if status < 200 or status >= 400:
        raise RunnerError(f"{url} returned HTTP {status}")
    return json.loads(body.decode("utf-8"))


def wait_for(name: str, url: str, *, json_expected: bool, timeout_seconds: int = 120) -> None:
    print(f"[wait] {name} {url}")
    deadline = time.time() + timeout_seconds
    last_error: Exception | None = None
    while time.time() < deadline:
        try:
            if json_expected:
                http_json(url, timeout=5)
            else:
                status, _ = http_get(url, timeout=5)
                if status < 200 or status >= 400:
                    raise RunnerError(f"HTTP {status}")
            print(f"[ok] {name} ready")
            return
        except Exception as exc:  # noqa: BLE001 - keep retrying transient startup failures.
            last_error = exc
            time.sleep(2)
    raise RunnerError(f"Timed out waiting for {name}: {last_error}")


def wait_for_all() -> None:
    wait_for("webapp-backend", f"{CENTRAL_BACKEND_URL}/health", json_expected=True)
    wait_for("file-server", f"{FILE_SERVER_URL}/health", json_expected=True)
    wait_for("webapp-frontend", CENTRAL_FRONTEND_URL, json_expected=False)
    wait_for("desktop-backend", f"{DESKTOP_BACKEND_URL}/health", json_expected=True)
    wait_for("desktop-frontend", DESKTOP_FRONTEND_URL, json_expected=False)


def seed_admin(root: Path) -> None:
    if is_windows() and (root / "scripts" / "seed-admin.ps1").exists():
        run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(root / "scripts" / "seed-admin.ps1"), "-EnvFile", str(root / ".env")], cwd=root)
        return
    run(compose_command(root, "exec", "-T", "webapp-backend", "python", "scripts/seed.py", include_dev=True), cwd=root)


def command_up(root: Path, install_mode: str) -> None:
    ensure_env(root)
    run(compose_command(root, "up", "-d", *DOCKER_SERVICES, include_dev=True), cwd=root)
    wait_for("webapp-backend", f"{CENTRAL_BACKEND_URL}/health", json_expected=True)
    seed_admin(root)
    python_exe = ensure_desktop_backend(root, install_mode)
    ensure_desktop_frontend(root, install_mode)
    start_desktop_processes(root, python_exe)
    wait_for_all()
    print_urls_and_credentials(root)


def command_down(root: Path) -> None:
    metadata = load_metadata(root)
    stop_pid(metadata.get("desktop_frontend_pid"), "desktop-frontend")
    stop_pid(metadata.get("desktop_backend_pid"), "desktop-backend")
    if metadata_path(root).exists():
        metadata_path(root).unlink()
    if is_windows() and (root / "scripts" / "dev-down.ps1").exists():
        run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(root / "scripts" / "dev-down.ps1"), "-EnvFile", str(root / ".env")], cwd=root)
    else:
        ensure_env(root)
        run(compose_command(root, "down", include_dev=True), cwd=root)


def command_health(root: Path) -> None:
    if is_windows() and (root / "scripts" / "dev-health.ps1").exists():
        run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(root / "scripts" / "dev-health.ps1")], cwd=root)
        return
    checks = [
        ("webapp-backend health", f"{CENTRAL_BACKEND_URL}/health", True),
        ("file-server health", f"{FILE_SERVER_URL}/health", True),
        ("webapp-frontend", CENTRAL_FRONTEND_URL, False),
        ("desktop-backend health", f"{DESKTOP_BACKEND_URL}/health", True),
        ("desktop-frontend", DESKTOP_FRONTEND_URL, False),
    ]
    for name, url, wants_json in checks:
        if wants_json:
            http_json(url)
        else:
            status, _ = http_get(url)
            if status < 200 or status >= 400:
                raise RunnerError(f"{name} returned HTTP {status}")
        print(f"[ok] {name} {url}")
    print("Health checks completed.")


def command_smoke(root: Path) -> None:
    if is_windows() and (root / "scripts" / "e2e-smoke.ps1").exists():
        run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(root / "scripts" / "e2e-smoke.ps1")], cwd=root)
        return
    command_health(root)
    env_values = read_env_file(root / ".env")
    email = env_values.get("ADMIN_EMAIL")
    password = env_values.get("ADMIN_PASSWORD")
    if not email or not password:
        raise RunnerError("ADMIN_EMAIL and ADMIN_PASSWORD must be set in .env for login smoke.")
    login_payload = json.dumps(
        {"email": email, "password": password, "device_fingerprint": "rsap-runner-smoke-test"}
    ).encode("utf-8")
    login_request = request.Request(
        f"{CENTRAL_BACKEND_URL}/api/v1/auth/login",
        data=login_payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with request.urlopen(login_request, timeout=15) as response:
        login = json.loads(response.read().decode("utf-8"))
    data = login.get("data") or {}
    access_token = data.get("access_token")
    session_token = data.get("session_token")
    if not access_token or not session_token:
        raise RunnerError("Login response did not contain both access_token and session_token")
    print("[pass] admin login returned JWT and X-Session-Token")
    me_request = request.Request(
        f"{CENTRAL_BACKEND_URL}/api/v1/auth/me",
        headers={"Authorization": f"Bearer {access_token}", "X-Session-Token": session_token},
        method="GET",
    )
    with request.urlopen(me_request, timeout=10):
        pass
    print("[pass] protected central request accepted dual-token headers")
    print("End-user smoke checks completed.")


def command_status(root: Path) -> None:
    print("Git")
    run_capture(["git", "branch", "--show-current"], cwd=root)
    run_capture(["git", "rev-parse", "HEAD"], cwd=root)
    print("\nDocker Compose")
    ensure_env(root)
    run_capture(compose_command(root, "ps", include_dev=True), cwd=root, check=False)
    metadata = load_metadata(root)
    print("\nRunner-managed desktop processes")
    backend_pid = metadata.get("desktop_backend_pid")
    frontend_pid = metadata.get("desktop_frontend_pid")
    print(f"  desktop-backend pid={backend_pid} alive={pid_alive(backend_pid)}")
    print(f"  desktop-frontend pid={frontend_pid} alive={pid_alive(frontend_pid)}")
    print_urls()


def print_urls() -> None:
    print("\nService URLs")
    print(f"  Central webapp:    {CENTRAL_FRONTEND_URL}")
    print(f"  Central backend:   {CENTRAL_BACKEND_URL}")
    print(f"  File server:       {FILE_SERVER_URL}")
    print(f"  Desktop backend:   {DESKTOP_BACKEND_URL}")
    print(f"  Desktop frontend:  {DESKTOP_FRONTEND_URL}")


def print_urls_and_credentials(root: Path) -> None:
    print_urls()
    env_values = read_env_file(root / ".env")
    print("\nLocal login")
    print(f"  Email:    {env_values.get('ADMIN_EMAIL', 'admin@rsap.local')}")
    print(f"  Password: {env_values.get('ADMIN_PASSWORD', 'admin123')}")
    print("\nRuntime logs")
    print(f"  {runtime_dir(root) / 'desktop-backend.log'}")
    print(f"  {runtime_dir(root) / 'desktop-frontend.log'}")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the complete RSAP local development runtime.")
    parser.add_argument("command", choices=["up", "down", "health", "smoke", "restart", "status"])
    install = parser.add_mutually_exclusive_group()
    install.add_argument("--install", action="store_true", help="Install desktop dependencies even if present.")
    install.add_argument("--no-install", action="store_true", help="Do not install missing desktop dependencies.")
    return parser.parse_args(argv)


def install_mode(args: argparse.Namespace) -> str:
    if args.install:
        return "always"
    if args.no_install:
        return "never"
    return "missing"


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    try:
        root = find_repo_root()
        os.chdir(root)
        if args.command == "up":
            command_up(root, install_mode(args))
        elif args.command == "down":
            command_down(root)
        elif args.command == "health":
            command_health(root)
        elif args.command == "smoke":
            command_smoke(root)
        elif args.command == "restart":
            command_down(root)
            command_up(root, install_mode(args))
        elif args.command == "status":
            command_status(root)
        return 0
    except (RunnerError, error.URLError, TimeoutError) as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
